server {
    listen 80;
    listen [::]:80;
    server_name convorocp.convoro.co;
    location /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
    location / { return 301 https://convorocp.convoro.co:8000$request_uri; }
}
